project_name: "snakeline"

cutadapt:
  fadapter: "AGATCGGAAGAGCACACGTCTGAACTCCAGTCA" # Forward Adapter
  radapter: "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT" # Reverse Adapter
  cut: 0
  min: 25
  quality_score: 15
  threads: 12 # Cannot be wrapped in quotes

fastqc:
  threads: 12

# Change star version to the star version you have installed by default it is star_v2.7.1a
# Changes to star_version needs to be updated on line 16 and 27 (Ex. star_v2.7.1a)
star_version: "star_v2.7.1a"

star_index:
  assembly_path: "/allen/programs/celltypes/workgroups/rnaseqanalysis/references/macaque/ncbi/mmul10/genome2/fasta/genome.fa"
  # GTF path needs to be added on line 21 and 38
  gtf_path: "/allen/programs/celltypes/workgroups/rnaseqanalysis/references/macaque/ncbi/mmul10/genome2/genes/genes.gtf"
  threads: 12
  numOverhang: "100"

star_nsupplied:
  threads: 12
  genome_dir: "/Pipeline/STAR/genome/star_v2.7.1a"

# If star index is present add into genome_dir key (Default is False, when no star directory is supplied)
star_supplied:
  threads: 24
  genome_dir: "/allen/programs/celltypes/workgroups/rnaseqanalysis/bnguy/Projects/other/rna_wkflow/04_18/Pipeline/STAR/genome/star_v2.7.1a/SAindex"
  # Example
  # genome_dir: "/allen/programs/celltypes/workgroups/rnaseqanalysis/references/macaque/ensembl/mmul10/genome/star_v2.7.10b"
  # /allen/programs/celltypes/workgroups/rnaseqanalysis/references/macaque/ncbi/mmul10/genome/star

stringTie:
  threads: 12
  gtf_path: "/allen/programs/celltypes/workgroups/rnaseqanalysis/references/macaque/ncbi/mmul10/genome2/genes/genes.gtf"

multiqc:
  threads: 12

default_resources:
  threads: 12
  mem_mb: 40000

#sample:
#  ['AB-BR3004-S001_E1-50_S1_L001', 'AB-BR3004-S002_E1-50_S2_L001', 'AB-BR3004-S003_E1-50_S3_L001', 'AB-BR3004-S004_E1-50_S4_L001', 'AB-BR3004-S005_E1-50_S5_L001', 'AB-BR3004-S006_E1-50_S6_L001', 'AB-BR3004-S007_E1-50_S7_L001']

sample:
